# Generated by Django 5.1.6 on 2025-02-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inor_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
